### ISSUE TITLE
Help me with a question, please!

### ISSUE THREAD

**Issue by guiananias** [Sharcoux/slider#1]
Hey! I'm using ~~(and loving)~~ your lib but I have two questions and I don't find any answer for this.

- Is there a way to remove *border-radius* of the track? I'm saying about the "circle" next to the thumb.
- Is there a way to add a minimum threshold value? I'm saying about always keeping a percentage *x* of the track always filled?

**Comment by Sharcoux** [comment]
Hi,
Thanks for your remark.
Can you update to v3.3.0 ?
I fixed the border-radius thing. Tell me if it seems ok to you.
About the threshold, I won't implement this, but there are a few solutions :

1) I added a trackStyle prop in v3.3, you could completely hide the track, and draw your own track below the slider which would be wider than the slider. Like if you want values between 10% and 90%, you could draw a track 20% wider than the slider.
2) You could make a PR to add the behavior that you want.

**Comment by guiananias** [comment]
Yeah! It's work! Thank you bro. You are the best!

I'm gonna up a PR to help you with this lib, i'm in loving with her. It's amazing. 

Thank you very much!

**Comment by Sharcoux** [comment]
@guiananias the thumb might be a bit too big so I made a fix for that in 3.3.1 to respect the thumbSize being provided.

**Comment by guiananias** [comment]
@Sharcoux yeah, I agree with you.

Another thing I would like to comment on is that there are still some performance issues, but nothing that interferes with the use.

**Comment by Sharcoux** [comment]
Oh really? Can you give me more details? I might need to look into it.

**Comment by Sharcoux** [comment]
Hi @guiananias , could you check the version 4.0.0?
Please try the AnimatedSlider (see the [Readme](https://github.com/Sharcoux/slider/blob/master/README.md)), maybe it can improve the performances.

**Comment by guiananias** [comment]
Hey @Sharcoux! How are you?

I will try that version! Thanks for letting me know about it!

**Comment by Sharcoux** [comment]
@guiananias Version 5.0.1 should be fixing a bunch of performance issues. Don't hesitate to tell me if you still encounter FPS drop.

**Comment by guiananias** [comment]
> @guiananias Version 5.0.1 should be fixing a bunch of performance issues. Don't hesitate to tell me if you still encounter FPS drop.

Wow!! This is really good.
We currently maintain the version of the package in v4.0.4, in a static way. I will talk to the team to update.

Any problem, I will report here.
