### ISSUE TITLE
[Android] seek progress glitches on 8.0.0

### ISSUE THREAD

**Issue by lovegaoshi** [Sharcoux/slider#101]
**Describe the bug**
Hi!  I use the slider as a track progress bar for a music app. since updating to 8.0.1, seeking on the progress bar glitches the current point back to 0/sometimes back at times. v7 works fine.

**To Reproduce**
This is the repo, to build, do yarn; cd example; yarn; yarn start.

https://github.com/lovegaoshi/react-native-track-player/tree/bug/slider

**Expected behavior**
see description.

**Screenshots**
n/A

**Please complete the following information:**

Android, slider lib v8

**Additional context**
N/A

**Comment by Sharcoux** [comment]
Can you provide a minimal reproducible example? Maybe on snack expo?

**Comment by tockv** [comment]
Seeing the same issue, and I believe it's a problem when using a controlled `value` prop.

I've made a demo on snack expo that shows the issue on both Android & iOS. As you drag the slider thumb back and forth, it fights over its position on the track between the actual value and another value (commonly 0).

https://snack.expo.dev/@jticknerfrogco/rn-slider-controlledvalue-issue?platform=android

As @lovegaoshi said, v7 works fine - it's just a problem in v8.

**Comment by Sharcoux** [comment]
Thanks a lot for the feedback and example. I noticed that some parts of the code got missing during the refacto of v8. It should be solved in v8.0.2. Please report any issue you might encounter with it.

**Comment by tockv** [comment]
@Sharcoux Yep, working now on 8.0.2. Just FYI, I think you left some logging turned on in the 8.0.2 release. Seeing `eventToValue` logs flooding my console

**Comment by lovegaoshi** [comment]
tysm! im not quite well versed in snack, really appreciate the example and
fix!
