### ISSUE TITLE
[rangeslider] max range now defaults to 0

### ISSUE THREAD

**Issue by lovegaoshi** [Sharcoux/slider#104]
**Describe the bug**
[on 8.0.5 now max range is 0 by default:](https://github.com/Sharcoux/slider/commit/70bd0c771bdc2b4d44eafbb2e171363494db88c4#diff-e356811945ab202b630fbb19ced04d4adfbf9c98b0f9e04000fe5c414cfeb718R45) minimumValue defaults to 0,  minimumRange 0, and minimumValue + minimumRange = 0

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Please complete the following information:**
n/a

**Additional context**
n/a

**Comment by Sharcoux** [comment]
Ah, damn. I should have make it a breaking change and update the readme accordingly. My bad. I'll fix asap.

**Comment by Sharcoux** [comment]
Solved in 8.0.6. Sorry for the mess. The new defaults will start from 9.0.0 and the documentation will be updated accordingly.
