### ISSUE TITLE
Feature request for range slider: disable crossing

### ISSUE THREAD

**Issue by avlonder** [Sharcoux/slider#11]
Hi,
I think the UX for the range slider could be improved significantly by using a prop that disables crossing:
in one swipe movement, you should stick to the thumb you grabbed first. This means that if you swipe the left thumb to a point beyond the right thumb, it stops at the location of the right thumb and nothing else happens to the right thumb.

**Comment by Sharcoux** [comment]
Ah, yes, indeed. I think that I could make them stop just one step before meeting, what do you think?
So, if for a range of [0, 10] I have a right thumb at 6, the left thumb could go only from 0 to 5.
I'll add an `allowCrossing` props defaulting to false.

It should be quick.

**Comment by Sharcoux** [comment]
Please try @sharcoux/slider@5.1.0 and report in case of issue
