### ISSUE TITLE
Difficult to grab thumb on Android device

### ISSUE THREAD

**Issue by avlonder** [Sharcoux/slider#12]
Hi

On my Motorola E6 Plus, it's extremely diffiicult to grab the thumb in both Slider and RangeSlider.
I tried crossingAllowed={false} (thanks for that, btw!) and slideOnTap={false}, and I tried to increase the thumb size, add additional margin, etc but this doesn't yield any improvement. I think something is wrong with the touchable area of the thumbs...

**Comment by Sharcoux** [comment]
Try this: `<Slider style={{ margin: 15 }} />`
The responder view is not the thumb or the track, but the slider itself.

**Comment by Sharcoux** [comment]
If this solves your issue, I will add a default style that includes this margin

**Comment by avlonder** [comment]
Hmm. Like I said: changing margins doesn't help, sorry. At least not on my device. But any way, maybe, if it's not a lot of work, you could add some animated response to the thumbs when selecting them (e.g. the Android native ripple and/or ios opacity change). Because I even don't know if it is caused by not being able to select the thumbs are not being able to move them. Often, I can move them once after hot reloading but then they seem to get stuck and I cannot move them at all.

**Comment by Sharcoux** [comment]
Interesting... I need to check what happens to the responder view. Do you have the issue with the snack I provided? I'll try it on my phone this week-end. I'm sure i can fix this.

**Comment by avlonder** [comment]
Ow! Of course! I know the cause: my sliders are inside a vertical scrollview. This probably is a hard one to solve :/

**Comment by avlonder** [comment]
And yes, the snack example works

**Comment by Sharcoux** [comment]
I received some messages, but you seem to have deleted them.
So, what is the current situation? Is there still an issue?

**Comment by avlonder** [comment]
For a brief moment, I was convinced that it was caused by the ScrollView container, but clearly it isn't. The minimal example with one slider and margin works. I've been trying to figure out what's breaking my screen with multiple sliders by gradually adding props and more sliders to the screen, but I can't figure it out (yet). Since your sliders don't use a native Android/iOS implementation I started thinking that it could be a general performance issue, but the performance monitor doesn't show frame drops.

**Comment by avlonder** [comment]
Omg. Instead of adding vertical margin, I had to add vertical padding and now it works!

**Comment by avlonder** [comment]
If you don't mind, could you add touch feedback similar to the callstack slider? So, for example, if you tap the thumb, the thumb's size increases. That would be great

**Comment by Sharcoux** [comment]
This could be achieved by making the thumbSize responding to the `onSlidingStart` and `onSlidingComplete` props.

So, `<Slider style={{ paddingTop: 10, paddingBottom: 10 }} />` solved the issue? Can you show the code that exactly solved the issue?

**Comment by avlonder** [comment]
Oh yes, great.

Yeah, simply add style={{ paddingVertical: 10 }} to the slider

**Comment by avlonder** [comment]
For the range slider, I cannot change the size of a single thumb. So maybe, the Android-like UX could be something you could still add.
