### ISSUE TITLE
minimumTrack and maximumTrack should use separate track styles

### ISSUE THREAD

**Issue by xam7247** [Sharcoux/slider#13]
@Sharcoux: Firstly, great lib :+1: :)

I am trying to make a slider, but without showing the thumb at all . I could only achieve it by styling both track and thumb with `borderRadius: 0`, but then I lose the nice rounded edges of track
<img width="288" alt="Screen Shot 2021-05-13 at 6 22 59 PM" src="https://user-images.githubusercontent.com/5365467/118129680-1f2b1a80-b41a-11eb-9e00-5bac0cacdaa8.png">

1. If I make thumbSize === trackSize (say: `thumbSize={4}`), its still visible as a circle between the track. 
<img width="363" alt="Screen Shot 2021-05-13 at 6 18 21 PM" src="https://user-images.githubusercontent.com/5365467/118129782-3a962580-b41a-11eb-957b-7b1274f8e790.png">

2. If I make thumbSize={0}, there is a black hole visible :sweat_smile:
<img width="287" alt="Screen Shot 2021-05-13 at 6 17 12 PM" src="https://user-images.githubusercontent.com/5365467/118130113-a2e50700-b41a-11eb-9cfa-bb0327aa2604.png">

Both #1 and #2 are due to minimumTrack's borderRadiusRight and maximumTrack's borderRadiusLeft showing up, since the two track elements in code are using the same styling / borderRadius.

I think if they use separate styles, i.e., `minimumTrack` with `borderRadiusRight: 0` and `maximumTrack` with `borderRadiusLeft: 0`, the track would still retain its nice rounded style, while providing us the ability to hide the thumb using same size as track. 

Thoughts or any other way to make this work ?

**Comment by Sharcoux** [comment]
I see. Let me give it a try. Can you just provide me a draft of what you want to achieve exactly to make sure that I understood correctly?

**Comment by Sharcoux** [comment]
Actually, just give a try at version 5.2.2

**Comment by xam7247** [comment]
> I see. Let me give it a try. Can you just provide me a draft of what you want to achieve exactly to make sure that I understood correctly?

Thanks for the prompt reply @Sharcoux. What I am looking for is to have a slider, without the thumb displayed, and the track having left and right border radius (similar to 1st image I posted, but with left border radius on track).

I'll try 5.2.2 and let you know.

**Comment by Sharcoux** [comment]
Ok, try version 5.3.0. I added:

```js
  minTrackStyle={undefined}         // Override the tracks' style for the minimum range
  midTrackStyle={undefined}         // Override the tracks' style for the middle range
  maxTrackStyle={undefined}         // Override the tracks' style for the maximum range
```

**Comment by xam7247** [comment]
@Sharcoux Thanks a bunch, works perfectly now :D. 👍 
I achieved my desired styling with: 
  thumbStyle: {
    borderRadius: 4,
    height: 4,
    width: 8
  },
  minTrackStyle:{
    borderRadius: 0,
    borderBottomLeftRadius: 4,
    borderTopLeftRadius: 4
  },
  maxTrackStyle: {
    borderRadius: 0,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4
  },

**Comment by Sharcoux** [comment]
In v 9.1.0, you can now provide a CustomTrack component to achieve this.
