### ISSUE TITLE
Can you library do this?

### ISSUE THREAD

**Issue by gruckionvit** [Sharcoux/slider#17]
Hi,

Cheers for making this, I need to create;

- a large slider with the ability to store the current focused value within the slider.
- Number scale along the top
- Icons along the bottom (that are in line with the number scale across the top, e.g. 0 on top icon-1 on bottom, 1 on top icon-2 on bottom.

<img width="515" alt="Screenshot 2021-06-18 at 10 00 04" src="https://user-images.githubusercontent.com/67283459/122535952-f64f0400-d01b-11eb-82b0-b8b072c036ab.png">

I can't show the icons that I have but they are faces in circles with a label underneath. So SVG or a component would be ideal. 

I am thinking of creating a wrapper component for the number scale, vertical lines, and icons with labels.

But the fat slider with the number inside, I am guessing this can't be achieved?

**Comment by Sharcoux** [comment]
You can achieve this by using this slider for the functional part, for drawing the rail and for drawing the plot.

For the numbers and the rest of your design, you'd probably better draw it behind the slider. Use the current value to update your component as desired.

Another option might be to create a component from scratch though.

**Comment by gruckionvit** [comment]
What about the extra large circle to hold the number? Any recommendations on how I can get the slider to look like that or if I'm being done externally how I can sync it's position with the main sliders position? (i'm guessing this will cause the UI to be choppy)

**Comment by Sharcoux** [comment]
I forgot about you, sorry ^^

Well, I'd say that you have a few options:

1. Get your designer fired, and hire someone less creative
2. Reduce your expectations or those of your client
3. Clone this lib and update the view so that it does what you expect it to do. You will see that the view is very basic, and you can probably update it to your needs.

See you mate

**Comment by Sharcoux** [comment]
For further references, version 6.1.0 add CustomThumb support. It should be possible to achieve what you want now.

**Comment by Sharcoux** [comment]
The new Version 7.0.1 provides native support for custom track marks. This should now be achievable.
