### ISSUE TITLE
Invariant Violation: Native module cannot be null

### ISSUE THREAD

**Issue by andyrobert3** [Sharcoux/slider#2]
First installed the library and using it prompts an error 

![image](https://user-images.githubusercontent.com/15076300/84570612-250b1c80-adc1-11ea-903b-2a2ac4d57aa4.png)

Steps taken:
1. Deleted node_modules & yarn install
2. pod deintegrate & pod install

Error still appears

**Comment by Sharcoux** [comment]
You should probably check on this side: https://github.com/react-native-community/push-notification-ios/issues/43
