### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by osilviotti** [Sharcoux/slider#20]
We're seeing division by zero errors when the minimum and maximum values are the same as there's logic in the library like the following:

`(value - minimumValue) / (maximumValue - minimumValue)`

It's happening for us as we're relying on data from an API and so we're having to force the maximumValue to be at least 1 to avoid red boxes in React Native as `NaN` is getting passed over the bridge.

I'm happy to open a PR to address the issue, I will just return 0 instead of running the calculation in the case that the minimum and the maximum value are the same.

**Comment by Sharcoux** [comment]
Hi!

Didn't thought of that. Let me fix it, I need 2 minutes.

**Comment by Sharcoux** [comment]
Try the version 5.4.2 released just now.

Just a thought though : you should probably reconsider what it means to have maximumValue = minimumValue, and especially what is the correct representation of this for the user. I seriously doubt that the Slider is a good representation of that case, and you should probably hide it and show something else when that case happens.

**Comment by osilviotti** [comment]
Oh wow, didn't expect a fix + release that quickly, I'd only just gone done making a coffee and forking the repo. Thanks!

In our use case, the slider is being used to display the progress of an audio file and sometimes we're getting audio files with a duration of 0 through. It's not really a great use case, but we're happy showing a slider that doesn't make sense in those rare occurrences we just thought that handling the division by zero would be better at a library level.

Thanks again :+1:

**Comment by osilviotti** [comment]
Just looking at the code for the fix, I think it's going to have unexpected behaviour. `x / 1` is `x`, not a percentage. I would've done something like this:

```js
const percentage = React.useMemo(() => {
  const divisor = maximumValue - minimumValue;
  return divisor === 0 ? 0 : (value - minimumValue) / divisor;
}, [value, minimumValue, maximumValue])
```

(or you could swap to `divisor === 0 ? 1` if you want it to fill by default)

For example, with the current code if min and max are passed in as 10 and value is passed in as 5 (which _shouldn't_ happen but `value` is controlled externally so is a possibility) then percentage would be 5 which is then passed in as props to both `Track` components which are expecting a value between 0 and 1.

This likely doesn't affect my specific use case so there no rush from me to get that changed, but thought I'd flag it in case you started seeing strange behaviour. I'm still happy to open a PR if you want me to make the changes

**Comment by Sharcoux** [comment]
The value is always rounded back to within the range [minValue, maxValue], so the result will always be 0 anyway

**Comment by Sharcoux** [comment]
Solved by [https://github.com/Sharcoux/slider/commit/5d31dff3fb4a6719a2eb7419ccff5cce3a34d967](https://github.com/Sharcoux/slider/commit/5d31dff3fb4a6719a2eb7419ccff5cce3a34d967)
