### ISSUE TITLE
Slider track does not render when vertical set to true

### ISSUE THREAD

**Issue by swgamerx** [Sharcoux/slider#22]
After setting `vertical` to true, only the thumb renders which stays stationary and will not slide.

**Comment by Sharcoux** [comment]
This seems weird. As you can see in the example, it is working as expected. The code is in the index.tsx file. Can you provide the slider configuration that you are using?

**Comment by swgamerx** [comment]
Just using a basic Slider setup with a value of 1 and vertical to true. 

![image](https://user-images.githubusercontent.com/6331758/139616853-f4dce359-164c-4f69-866f-e7fcbdd18e06.png)

**Comment by swgamerx** [comment]
what does the code look like for the example in the gif?

**Comment by Sharcoux** [comment]
[Here](https://snack.expo.dev/AF9len8WS) you can find a working demo of your use case. I tested on web, Android and iOS. Working as expected.

[Here](https://github.com/Sharcoux/slider/blob/master/index.tsx) You can find the code that generated the gif.

**Comment by Sharcoux** [comment]
I Think that your issue comes from your style. Your slider might automatically spread horizontally, but not vertically, giving it a 0-height size

**Comment by swgamerx** [comment]
interesting, the first snippet didn't work, but the second did, something about the styles. 

![image](https://user-images.githubusercontent.com/6331758/139618184-52e8914c-59f8-484c-82c2-8440c733d2b7.png)

**Comment by Sharcoux** [comment]
As I said, your style probably doesn't apply any height to your slider. You need to work on your layout strategy. Remember that React Native uses flex layout.
