### ISSUE TITLE
Slider not have smooth animation when inside scrollview

### ISSUE THREAD

**Issue by igorwessel** [Sharcoux/slider#23]
Thanks for this amazing library.

When the slider is inside a scroll view and happens to have items to enable scrolling, The animation is very slow, I believe the entire screen is being re-rendered every time we change the value on the slide. 
The heavier this page is, the animation becomes slower, in this example I didn't have many heavy items to re-render again.

https://user-images.githubusercontent.com/54173994/140517649-41a20ac2-f12b-4ba3-95e0-65d7498785c5.mp4

I haven't been able to find a solution to this yet.

**Comment by 0rsa** [comment]
I have also an animation performance issue and my Slider isn't in a scrollview

**Comment by Sharcoux** [comment]
@0rsa @igorwessel Tell me if you still have an issue with the version 5.6.0

Thanks for the feedback.
