### ISSUE TITLE
onSlidingComplete triggers at first render

### ISSUE THREAD

**Issue by 0rsa** [Sharcoux/slider#24]
Hi,
I switched from community slider to this.
onSlidingComplete behaviour is different and triggers when the slider is rendered.
Is it an expected behaviour? Is there a way to disable it?
Thank you

**Comment by Sharcoux** [comment]
Definitely not an expected behaviour

Can you tell me if you still have the issue with version 5.6.0 I just released?

**Comment by 0rsa** [comment]
This is OK with 5.6.0!
Thank you
