### ISSUE TITLE
Vertical Slider jump to big number in iOS

### ISSUE THREAD

**Issue by rachellauyui** [Sharcoux/slider#26]
I am very new to React Native. When I use the slider with vertical+{true} and inverted={true}, it works fine in Android. But in iOS, a slight touch will make the thumb jump a long way. I am using the slider to zoom a camera, and the camera will zoom to maximum with a slight touch. I wonder if other people face the same problem? Thanks!

**Comment by Sharcoux** [comment]
Please publish here the configuration you are using for the slider, including the styles

**Comment by rachellauyui** [comment]
Thank you VERY muc for your quick reply. Here it is. I use a PNG file as thumb image. It is my first time leaving message in github, apologies if I did not provide all the information.

<View style={{
  flex:1,
  backgroundColor:'transparent',
  }}>
<Slider
        style={{
          width:400,
          height:100,  
          alignItems:"flex-end",
          paddingEnd: 50,
          backgroundColor:"transparent",
           }}
        vertical={true}
        inverted={true}
        thumbImage={require('../icon/zoom1.png')}
        thumbSize={45}
        thumbTintColor={'grey'}
        minimumValue={0}
        maximumValue={1}
        step={0}
        value={0}
        onValueChange={(value) => setZoomValue(value)}
        minimumTrackTintColor={'white'}
        maximumTrackTintColor={'white'}
        />
</View>

**Comment by rachellauyui** [comment]
BTW, I use another horizontal slider too, and it works perfectly both in Android and iOS:

<View style={{backgroundColor:"transparent",flex:1, alignItems:"flex-end", width:width, paddingRight:30, paddingLeft:50}}>       
<Slider
        style={{
          width:'100%',
          height:150,
          backgroundColor:"transparent",
          justifyContent: "flex-start",
          transform:[{translateY:0}]
          }}
        thumbImage={require('../icon/bright1.png')}
        thumbTintColor={'black'}
        minimumValue={0}
        maximumValue={1}
        thumbTouchSize={{width: 200, height: 200}}
        value={0.65}
        onValueChange={(value) => setLight(value)}
        minimumTrackTintColor={'white'}
        maximumTrackTintColor={'white'}
      />

</View>

**Comment by Sharcoux** [comment]
Why do you specify `alignItems: 'flex-end'`? It might be the cause of the issue.

You should use `useCallback` to define the function `onValueChange`. Also, you can write `thumbTintColor='grey'` instead of `{'grey'}`. And `vertical` instead of `vertical={true}`.

Finally, if you are using a static style as you do here, you shall use `Stylesheets`.

**Comment by rachellauyui** [comment]
After further testing, the slider works fine in iOS, even with flexEnd. I am using slider to control zoom of camera. iPhone can zoom A LOT CLOSER than Android, thus slightly move the thumb will zoom in a lot. 

My apologies for the false alarm!
