### ISSUE TITLE
scroll issue

### ISSUE THREAD

**Issue by Bamorem** [Sharcoux/slider#27]
When you use RangeSlider and Slider inside a ScrollView and you want to scroll horizontally, but you slide a bit vertically the slider loose the focus and only the ScrollView is sliding.

**Comment by Sharcoux** [comment]
You should probably use a padding around the slider to increase the responder area.

If that doesn't solve the issue, can you create a snack to illustrate the issue? I'll fix it if I can.

**Comment by leaky** [comment]
I can confirm this is an issue as I'm experiencing a similar thing. I have a slider embedded inside of a [BottomSheet](https://github.com/gorhom/react-native-bottom-sheet) and when panning gestures are enabled on the BottomSheet the slider is incredibly sticky, moving only a max of 3/4 steps per slide gesture. When I disable the panning gestures on the BottomSheet the slider's performance is as expected with the steps incrementing relative to the full slide gesture. I haven't built a snack for this but believe I've given you everything there to reproduce the issue.

**Comment by Sharcoux** [comment]
@leaky you problem seems related to [this bug](https://github.com/Sharcoux/slider/issues/15)

**Comment by Sharcoux** [comment]
@Bamorem , due to inactivity, I will close this bug. Thanks for your feedback.
