### ISSUE TITLE
RangeSlider is bugged on start?

### ISSUE THREAD

**Issue by hiwyn** [Sharcoux/slider#28]
Is `RangeSlider` is bugged on start or i'm doing something wrong?
I did this:
```ts
  const [minAge, setMinAge] = useState(18);
  const [maxAge, setMaxAge] = useState(50);
...
        <Text style={{ marginVertical: 15 }}>
          minAge: {minAge} maxAge: {maxAge}
        </Text>
        <RangeSlider
          range={[18, 100]} // set the current slider's value
          minimumValue={18} // Minimum value
          maximumValue={100} // Maximum value
          step={0} // The step for the slider (0 means that the slider will handle any decimal value within the range [min, max])
          minimumRange={0 || 10} // Minimum range between the two thumbs
          crossingAllowed={false} // If true, the user can make one thumb cross over the second thumb
          outboundColor={colors.light_gray} // The track color outside the current range value
          inboundColor={colors.red} // The track color inside the current range value
          thumbTintColor={colors.white} // The color of the slider's thumb
          thumbStyle={{
            width: 24,
            height: 24,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: colors.dark_gray,
          }} // Override the thumb's style
          trackStyle={{ height: 4 }} // Override the tracks' style
          minTrackStyle={undefined} // Override the tracks' style for the minimum range
          midTrackStyle={undefined} // Override the tracks' style for the middle range
          maxTrackStyle={undefined} // Override the tracks' style for the maximum range
          vertical={false} // If true, the slider will be drawn vertically
          inverted={false} // If true, min value will be on the right, and max on the left
          enabled={true} // If false, the slider won't respond to touches anymore
          trackHeight={4} // The track's height in pixel
          thumbSize={15} // The thumb's size in pixel
          thumbImage={undefined} // An image that would represent the thumb
          slideOnTap={true} // If true, touching the slider will update it's value. No need to slide the thumb.
          onValueChange={(e) => {
            setMinAge(Math.floor(e[0]));
            setMaxAge(Math.floor(e[1]));
          }} // Called each time the value changed. The type is (range: [number, number]) => void
          onSlidingStart={undefined} // Called when the slider is pressed. The type is (range: [number, number]) => void
          onSlidingComplete={undefined} // Called when the press is released. The type is (range: [number, number]) => void
        />
```
but it starts:
https://i.imgur.com/58ggYEA.png
its like 50 is the limit, but its not, its 100

and when i move the right ball it just fix, like u can see on this image:
https://i.imgur.com/b23D6Li.png

but if i move the left ball it but the right value:
https://i.imgur.com/R1GCSQk.png

is this a bug or i'm doing something wrong?

**Comment by Sharcoux** [comment]
You set maxAge to 50:

` const [maxAge, setMaxAge] = useState(50);`

You write "maxAge: 50"

` maxAge: {maxAge}`

You set the current max value to 100:

` range={[18, 100]}`

So, yeah, the slider starts with 100 as starting max value, and the fact that you display "50" above doesn't change anything.

**Comment by hiwyn** [comment]
> You set maxAge to 50:
> 
> ` const [maxAge, setMaxAge] = useState(50);`
> 
> You write "maxAge: 50"
> 
> ` maxAge: {maxAge}`
> 
> You set the current max value to 100:
> 
> ` range={[18, 100]}`
> 
> So, yeah, the slider starts with 100 as starting max value, and the fact that you display "50" above doesn't change anything.

but the progress bar is showing 50 like 100
look: its totally filled: https://i.imgur.com/58ggYEA.png
(idk if there is a bug or if i'm doing some shit)

it shouldn't start with the right side of the bar gray?
like this, after i push the right ball to the left?
blob:https://imgur.com/2b43fed0-81cf-4763-b443-f302c7565222

**Comment by Sharcoux** [comment]
Read better. You are setting the max **value** to **100**. So the slider behaves like you told him to : representing the range [18, 100]. Why would its max value be 50 if you never set it to 50?

**Comment by hiwyn** [comment]
> Read better. You are setting the max **value** to **100**. So the slider behaves like you told him to : representing the range [18, 100]. Why would its max value be 50 if you never set it to 50?

`maxAge` was a bad variable name, i just did this bar to test your lib
maxAge in my case means the maxAge selected in the rangeSliderBar
its not the maxValue for the bar, max value to the base should be 100, but the user start with 50 selected

my problem is with start value
like in your component `Slider` i could just set a value={50}
in this `RangeSlider` i can't, or can i?

**Comment by hiwyn** [comment]
test this code:
```ts
const [minAge, setMinAge] = useState(18);
const [maxAge, setMaxAge] = useState(50);

<Text style={{ marginVertical: 15 }}>
minAge: {minAge} maxAge: {maxAge}
</Text>

<RangeSlider
range={[18, 100]} // set the current slider's value
minimumValue={18} // Minimum value
maximumValue={50} // Maximum value
step={0} // The step for the slider (0 means that the slider will handle any decimal value within the range [min, max])
minimumRange={10} // Minimum range between the two thumbs
crossingAllowed={false} // If true, the user can make one thumb cross over the second thumb
outboundColor="#E0E0E0" // The track color outside the current range value
inboundColor="#FB0404" // The track color inside the current range value
thumbTintColor="#FFF" // The color of the slider's thumb
thumbStyle={{
  width: 24,
  height: 24,
  borderRadius: 12,
  borderWidth: 1,
  borderColor: "#757575",
}} // Override the thumb's style
trackStyle={{ height: 4 }} // Override the tracks' style
minTrackStyle={undefined} // Override the tracks' style for the minimum range
midTrackStyle={undefined} // Override the tracks' style for the middle range
maxTrackStyle={undefined} // Override the tracks' style for the maximum range
vertical={false} // If true, the slider will be drawn vertically
inverted={false} // If true, min value will be on the right, and max on the left
enabled={true} // If false, the slider won't respond to touches anymore
trackHeight={4} // The track's height in pixel
thumbSize={15} // The thumb's size in pixel
thumbImage={undefined} // An image that would represent the thumb
slideOnTap={true} // If true, touching the slider will update it's value. No need to slide the thumb.
onValueChange={(e) => {
  setMinAge(Math.floor(e[0]));
  setMaxAge(Math.floor(e[1]));
}} // Called each time the value changed. The type is (range: [number, number]) => void
onSlidingStart={undefined} // Called when the slider is pressed. The type is (range: [number, number]) => void
onSlidingComplete={undefined} // Called when the press is released. The type is (range: [number, number]) => void
/>
```
it simple does not work
right ball just cant move

i just wanted to the slider looks like this: https://i.imgur.com/ObOVBeT.png

**Comment by hiwyn** [comment]
i find what i was doing wrong
i shouldn't not using `onValueChange` to set the states, your lib is working, i just have to set `range={[minAge, maxAge]}`
and set the values in `onSlidingComplete` instead of `onValueChange`, changing on onValueChange that was bugging everything

**Comment by Sharcoux** [comment]
You can do whatever you want within onValueChange or onSlidingComplete, but if you do `range={[18, 100]}`, it sets the value to [18, 100]. If you do ` range={[minAge, maxAge]}` , it sets the range to [minAge, maxAge], and is minAge=18 and maxAge=50, then ` range={[minAge, maxAge]}` sets the range to [18, 50].

If this is your code:

![image](https://user-images.githubusercontent.com/797545/148444604-70b47a66-ed64-48c8-80bb-d47428326b6a.png)

Then of course, the range slider represents the range [18, 100].

**Comment by hiwyn** [comment]
> You can do whatever you want within onValueChange or onSlidingComplete, but if you do `range={[18, 100]}`, it sets the value to [18, 100]. If you do ` range={[minAge, maxAge]}` , it sets the range to [minAge, maxAge], and if minAge=18 and maxAge=50, then ` range={[minAge, maxAge]}` sets the range to [18, 50].
> 
> If this is your code:
> 
> ![image](https://user-images.githubusercontent.com/797545/148444604-70b47a66-ed64-48c8-80bb-d47428326b6a.png)
> 
> Then of course, the range slider represents the range [18, 100].

You are right that was the first main error, but when i change range to states and drag the bar, the bar broke starts to grow and shrink in a infinite loop, so i did think that i made something wrong
when i change to onSlidingComplete it also fix

**Comment by hiwyn** [comment]
Btw nice lib, better then expo suggest! Thank you for this ;)
