### ISSUE TITLE
Controlled value

### ISSUE THREAD

**Issue by jb-5murf** [Sharcoux/slider#29]
Hi. Is it possible to change the slider value programmatically? Or do you plan to implement the value prop as controlled value? Thanks

**Comment by Sharcoux** [comment]
I don't understand the question. If you change the `value` prop, it will change the slider representation, doesn't it? If you have an issue please provide a snack or a codesandbox to demonstrate the issue.

**Comment by jb-5murf** [comment]
https://snack.expo.dev/@jb5/slider Here is a simple snack. Clicking the buttons changes the value, but the slider doesn`t move.

**Comment by Sharcoux** [comment]
Fixed in V. 5.6.2

Tell me if it's ok for you.

Thanks a lot for your feedback.

**Comment by jb-5murf** [comment]
Works great! Thank you very much for superfast update!

**Comment by Sharcoux** [comment]
You're welcome. I don't know how I missed that in the last release.
