### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name ARTSurfaceView

### ISSUE THREAD

**Issue by moriyuu** [Sharcoux/slider#3]
![image](https://user-images.githubusercontent.com/20125542/84892780-27c78380-b0d9-11ea-9770-a7d2c7ba3aa1.png)

Error occurred at ios simulator. But no error with react-native-web.

react: 16.9.0
react-native: 0.61.4
@sharcoux/slider: ^3.3.1

**Comment by Sharcoux** [comment]
I hardy believe that this is linked with this slider. The slider is just using the basic View component.
