### ISSUE TITLE
Failed prop type: Invalid props.style key `userSelect` supplied to `Image` when using custom Thumb Image

### ISSUE THREAD

**Issue by rachellauyui** [Sharcoux/slider#39]
Hi! When I supply a custom Thumb Image to the slider, the warning "Failed prop type: Invalid props.style key userSelect supplied to Image" shows up.

My code of the slider:
                    <Slider
                      style={{
                        width: "90%",
                        height: 20,
                        backgroundColor: "transparent",
                        justifyContent: "flex-start",
                      }}
                      thumbImage={require("../icon/bright1.png")}
                      thumbSize={50}
                      thumbTintColor="transparent"
                      minimumValue={0}
                      maximumValue={1}
                      value={0.65}
                      onValueChange={(value) => setLight(value)}
                      minimumTrackTintColor="white"
                      maximumTrackTintColor="white"
                    />

The full error message is:
Warning: Failed prop type: Invalid props.style key `userSelect` supplied to `Image`.
Bad object: {
  "width": 45,
  "height": 45,
  "backgroundColor": "grey",
  "zIndex": 1,
  "borderRadius": 22.5,
  "overflow": "hidden",
  "userSelect": "none"
}
Valid keys: [
  "display",
  "width",
  "height",
  "start",
  "end",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginEnd",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingEnd",
  "borderWidth",
  "borderTopWidth",
  "borderStartWidth",
  "borderEndWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "resizeMode",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderRadius",
  "overflow",
  "tintColor",
  "opacity",
  "overlayColor",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius"
]

Would you kindly check what is the problem please? Thanks!

**Comment by Sharcoux** [comment]
Oh, ok, I didn't use yet the thumbImage prop. So, notice that it's just a warning. It should not have any impact on your code. I'm gonna fix the warning. If you have issues with your usage of thumbImage, don't hesitate to report here, as I didn't test it yet.

**Comment by Sharcoux** [comment]
Fixed in 6.0.2

Open a new issue for problems with the thumbImage

**Comment by rachellauyui** [comment]
I used sharcoux 5.6.1 before, but the thumb freezed, cannot moved at all. And when I upgraded to 6.0.2, it crashed with below message:
Invariant Violation: "cursor" is not a valid style property.
StyleSheet view: {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "auto",
  "alignItems": "center",
  "cursor": "pointer",
  "userSelect": "none"
}

And also below error message that I assume is a red herring related to the problem of the cursor:
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

Here is a list of dependencies if it helps:
"dependencies": {
    "@babel/core": "^7.17.5",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-navigation/drawer": "^6.1.6",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/stack": "^6.0.11",
    "@sharcoux/slider": "^6.0.2",
    "expo": "^44.0.0",
    "expo-ads-facebook": "~11.1.0",
    "expo-app-loading": "~1.3.0",
    "expo-asset": "~8.4.6",
    "expo-brightness": "^10.1.1",
    "expo-camera": "^12.1.2",
    "expo-cli": "^5.3.1",
    "expo-dev-client": "~0.8.4",
    "expo-image-manipulator": "~10.2.0",
    "expo-in-app-purchases": "^12.1.1",
    "expo-keep-awake": "~10.0.1",
    "expo-linking": "~3.0.0",
    "expo-media-library": "~14.0.0",
    "expo-navigation-bar": "~1.1.1",
    "expo-sharing": "~10.1.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-store-review": "~5.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-applovin-max": "^3.0.2",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-onboarding-swiper": "^1.2.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1"
  },

I am using Expo and this is the babel.config.js:
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};


I wonder if you have time to look into it. Thanks!

**Comment by Sharcoux** [comment]
This was fixed in version 6.0.3. Thanks a lot for your comments and help. Don't hesitate if you notice other issues.

**Comment by rachellauyui** [comment]
Hi, have updated to 6.0.3. iOS works fine. But Android custom thumb is sticky, non-responsive. Need to push and poke many times and maybe the thumb jumps once.  I use both a horizontal and a vertical slider. The funny thing is that only horizontal slider in Android has this problem. Thanks!

**Comment by Sharcoux** [comment]
Are there other gesture handler in your code around your slider? Otherwise, try to add a padding around the slider. It should work. I'll try to add a snack demo later.

**Comment by rachellauyui** [comment]
Yes, there is another pressable nearby that interfered with the thumb. Once the presable is moved away, it works perfectly!! Thanks a lot!
