### ISSUE TITLE
RN StyleSheet.validate throws in native environments (`userSelect` and `cursor` properties)

### ISSUE THREAD

**Issue by matthewstyers** [Sharcoux/slider#41]
In iOS/Android environments, React Native's StyleSheet.validate throws the error reported in #39, but for both the `cursor` and `userSelect` properties. Additionally, the error occurs during the initial import, so the package can't be referenced in any import statement.

React Native: 0.64
Platform: iOS/Android

(PR incoming)

**Comment by sadia-onyxtec** [comment]
I am still facing this issue after updating to ^5.6.5!

**Comment by Sharcoux** [comment]
Yep. As mentioned in the PR, you need to upgrade to v 6.0.3 :wink:
