### ISSUE TITLE
Step props is not working

### ISSUE THREAD

**Issue by johnlim5847** [Sharcoux/slider#5]
Hi, I tried to pass in 10 as the `step` but the value is still increased by 1 instead of 10.

**Comment by Sharcoux** [comment]
I'll check that. Thanks for the remark. Can you provide the full configuration of the slider?

**Comment by Sharcoux** [comment]
@johnlim5847 Indeed. I'm fixing it right now. Thanks for the feedback. It will be live in a few minutes.

**Comment by Sharcoux** [comment]
Fixed in version 4.0.5
Feel free to reopen if you still have an issue.

**Comment by johnlim5847** [comment]
wow, that was fast @Sharcoux ! thanks for the quick response and hard work, much appreciated! :)

**Comment by ahmad6242** [comment]
Hello, 
step is not working in RangeSlider!

**Comment by Sharcoux** [comment]
Really? Let me check that

**Comment by Sharcoux** [comment]
Can you provide the config that you have been using?

**Comment by Sharcoux** [comment]
@ahmad6242 Check the file index.tsx in the root of `node_modules/@sharcoux/slider`. You will see an example of RangeSlider using steps. If you check the gif that is shown in the readme, you will see that it's working as expected.

I'll need your configuration to be able to investigate further.

**Comment by ahmad6242** [comment]
I am using  "@sharcoux/slider": "^5.4.3",
```
import { RangeSlider } from '@sharcoux/slider'
//this.state.endTime.duration = time in seconds
<RangeSlider
                                        style={{ flex: 1 }}
                                        slideOnTap={false}
                                        range={[0, this.state.endTime.duration]}                    // set the current slider's value
                                        minimumValue={0}                  // Minimum value
                                        maximumValue={this.state.videoData.duration}                  // Maximum value
                                        step={1}                          // The step for the slider (0 means that the slider will handle any decimal value within the range [min, max])
                                        minimumRange={0.1}          // Minimum range between the two thumbs
                                        outboundColor={themeColors.lightGrey}              // The track color outside the current range value
                                        inboundColor={themeColors.info3}         // The track color inside the current range value
                                        thumbTintColor={themeColors.grey}         // The color of the slider's thumb
                                        thumbStyle={{ borderRadius: 100 }}            // Override the thumb's style
                                        trackStyle={undefined}            // Override the tracks' style
                                        enabled={false}                    // If false, the slider won't respond to touches anymore
                                        trackHeight={5}                   // The track's height in pixel
                                        thumbSize={20}                    // The thumb's size in pixel
                                        onValueChange={(range) => {
                                            console.log('range', range);
                                            this.setState({ startTime: range[0], endTime: range[1] })
                                           

                                        }}
                                    // onSlidingStart={() => this.setState({ scrollEnabled: false })}
                                    // onSlidingComplete={() => this.setState({ scrollEnabled: true })}
                                    />
```

**Comment by Sharcoux** [comment]
Can you check the value of `this.state.videoData.duration`?

**Comment by ahmad6242** [comment]
duration: 13.013 @Sharcoux

**Comment by Sharcoux** [comment]
First thing, you should probably:
1) Remove enabled={false} which totally disable the response to touches
2) Remove slideOnTap={false} to make it response to touches even when slightly aside from the thumb

**Comment by ahmad6242** [comment]
Sorry, i was having these just for some other test. 
Both properties are removed and still its the same.

**Comment by Sharcoux** [comment]
Indeed, when the min or max values don't match the precision of the step, the calculation is wrong. I'll fix that.

I'll try to increase the size of the responding area when `slideOnTap` is false. 

But when slideOnTap is unset or true, I didn't notice anything about the slider not responding. Is this still happening?

Anyway, the fix should be out in an hour top

**Comment by ahmad6242** [comment]
yes its not responding very well. 
And i set slideOnTap=false because when i try to move the End Cursor it moves the Start cursor to the end frequently. 
I think the not responding thing is because of the step. When this will be corrected the response will be automatically corrected. 
Many Thanks for your help. 

![image](https://user-images.githubusercontent.com/12858657/134905431-212e347c-a847-4d2e-9108-2a462ab8af85.png)

**Comment by ahmad6242** [comment]
And ,
How can i change the Selected range value through a Method! 
Is that possible? 
Because there is nothing in the documentation about that.

**Comment by Sharcoux** [comment]
Ok, You can try the version 5.5.0

About your last question, I'm not sure about what you are trying to achieve. If you want to change the current range value, just change the value provided in the `range` prop.

If you want this to be done with a method, just use imperative handles:

```ts
const [range, setRange] = React.useState<[number, number]>([0, 100])
React.useImperativeHandle(ref, { setRange }, [])
return <Slider range={range} onValueChange={setRange} ... />
```

**Comment by ahmad6242** [comment]
Okey Thanks.

**Comment by ahmad6242** [comment]
What i am trying to achieve is that, when I click these buttons. It will forward the value to like 5 second. 
I want the cursors also to move to the updated value. 
I have tried updating like
```
range={[this.state.startTime, this.state.endTime]}
```
but its not working like this

![image](https://user-images.githubusercontent.com/12858657/134910634-27e28779-927b-47a9-90c6-7c116ad92faa.png)

**Comment by Sharcoux** [comment]
Indeed. The value is not updated in range slider when providing a new value... :/

Gonna fix it

**Comment by ahmad6242** [comment]
I appreciate it. Many more thanks. Just tag me when you complete these.

**Comment by Sharcoux** [comment]
@ahmad6242 Done. You can update to the 5.5.1. Thanks for the feedback :+1:

**Comment by ahmad6242** [comment]
Perfect , values are getting updated in Range<Prop> and Step is also working.
Have you increased the touchable area for the thumbs? Its still difficult to move it.

**Comment by Sharcoux** [comment]
On what device are you testing? Web, Android or iOS? Anyway, check the height of the slider. I bet that the height is very narrow and that's why it doesn't respond. Try adding a height to the slider's style.

**Comment by ahmad6242** [comment]
You bet you Win. Perfect!. Height works. 
Thank you so much.
