### ISSUE TITLE
Allow selecting the same min and max value for the RangeSlider on drag.

### ISSUE THREAD

**Issue by shashank1010** [Sharcoux/slider#50]
Firstly, I've looked at the old bugs, and I really appreciate your fixes that usually come within minutes. Kudos to you

I think, In a range slider, sometimes the minValue and maxValue can be the same. However, at present, I don't think this range slider supports dragging the handles to the same min and max values. 

I've created a demo:
https://codesandbox.io/s/sharcoux-slider-bug-demo-28w5nf?file=/src/App.js

Several things are happening here..

1. if I make the range [0,0] it works fine
2. if I make the range [10,10], on drag, the value is updated as such [9, 11], [8, 11] and so ..
3. if I start with different values and I want to make min and max values same, it's just not possible.

Possible solution would be to accept `allowSameValues`, prop and if set to true and values are equal, update the value for the current drag handle min/max to the new equal value :)

I'd make `allowSameValues` by default false so that it doesn't break anything for people already using the library..

**Comment by Sharcoux** [comment]
Yep. There is definitely something wrong here. I'll have a look at it. I'm sick right now, but if you don't have news by monday, feel free to ask for news.

**Comment by Sharcoux** [comment]
Ok, the crossingAllowed prop was actually completely broken.  It's fixed in version `@Sharcoux/slider: 6.1.0`. The `crossingAllowed` prop will automatically consider that the thumbs can join as the feeling would be weird if you can cross without joining.

Feedback appreciated.

**Comment by shashank1010** [comment]
It works!!


I have only tested this in the browser, I'm going to run some tests in the mobile and update really soon!
