### ISSUE TITLE
Tooltip selected value above the thumb.

### ISSUE THREAD

**Issue by shashank1010** [Sharcoux/slider#51]
Is there a way to display the current values above the thumbs and have custom thumbs?

Reference:
https://m3.material.io/components/sliders/overview#65a5e5f9-2aa3-44b5-ad8e-73cf2694975e

**Comment by Sharcoux** [comment]
I added a CustomThumb prop on version 6.1.0. Tell me if it suits your needs.

**Comment by shashank1010** [comment]
It works, however, to make it to work, I had to duplicate the thumb component you have written.
The problem was, I thought it would work out of the box.
I had to add `pointer-events="none"` to my view to make it work.

Adding a note about this will save questions. Alternately, you could simply render it in a View with pointer-events="none" :)

Great going.

Thanks for your effort!

**Comment by Sharcoux** [comment]
Duplicate the thumb component? What do you mean?

About the "pointer-events" thing, it's fixed in the version 6.1.1. Thanks for reporting.

**Comment by Sharcoux** [comment]
Without no further comment, I will close this thread.
