### ISSUE TITLE
[iOS] The slide handle isn't easily picked up when you attempt to slide it

### ISSUE THREAD

**Issue by TowhidKashem** [Sharcoux/slider#7]
Thanks for the lib! I was very excited about it since the community slider didn't allow thumb size to be changed, everything in this lib looked good while setting it up in the simulator but when I tried to use it on a real device (iPhone 11 IOS 14) it was hard to scroll the slider. It wasn't always picked up when you tried to move it with the fingers, it look a couple tries at times to move it. Unfortunately it's not really usable until this is fixed.

My code:

```
<Slider
  value={50}
  minimumValue={0}
  maximumValue={100}
  step={1}
  minimumTrackTintColor={colors.pastelBlue}
  maximumTrackTintColor="#ccc"
  thumbTintColor={colors.pastelBlue}
  trackHeight={6}
  thumbSize={20}
  onValueChange={volume => onVolumeChange(volume)}
/>
```

Maybe if some sensitivity setting is increased it would solve the issue..

**Comment by Sharcoux** [comment]
That's annoying indeed. Unfortunately, I don't have an iPhone to try and fix this. Also, if it works on the emulator, the issue might possibly not come from the lib. Do you think that you could check what part exactly is not being triggered? You will find that part in the ResponderView.
Could it be that the pointerEvent =none on the thumb is being ignored? Is it working better when sliding directly on the track and ignoring the thumb?

**Comment by BATTLEROYALXS** [comment]
Hello, thank for your repo, i see this problem too for my part

**Comment by Sharcoux** [comment]
@BATTLEROYALXS Could you make the same test I asked @TowhidKashem ? That would be helpful to solve the problem as I don't have an device form apple to try this out.

**Comment by Sharcoux** [comment]
@TowhidKashem can you explain why you closed the issue? How did you solve it?

**Comment by TowhidKashem** [comment]
Hey,

I didn't solve it, just went back to using this one:

https://github.com/callstack/react-native-slider

which doesn't have the issue. For what it's worth I also tried to use this lib:

https://github.com/jeanregisser/react-native-slider

which also had the same issue as yours. The only one that didn't was the community slider.

I re-opened the issue if that helps but I'm bowing out of the thread because I'm satisfied with the community slider even with it's shortcomings. If it gets fixed feel free to close this or if you need me to do it just @ me and I will.

**Comment by Sharcoux** [comment]
@TowhidKashem @BATTLEROYALXS  For some reasons the ultimate version might have solved the issue you encountered. Could you try to see if you can replicate the issue with version 5.0.3?

Thanks!

**Comment by inhyuk-jung** [comment]
@TowhidKashem @BATTLEROYALXS I got trick to solve this issue.

```
         <Slider
              style={{width: "70%", marginLeft: 10, marginRight: 10}}
              minimumValue={0}
              maximumValue={5}
              step={0.1}
              trackStyle={{marginTop: 9, marginBottom: 9}}  
              trackHeight={1}  
              thumbSize={20}
              value={this.state.textKern}
              onValueChange={this.handleLeadThrottled}
              thumbTintColor="#CEC9FF"
              minimumTrackTintColor="#CEC9FF"
              maximumTrackTintColor="#C0C0C1"
            />
```

You should focus ` trackStyle={{marginTop: 9, marginBottom: 9}}  `.

**Comment by Sharcoux** [comment]
Ah, their problem was the touch area you think? Maybe I should give it a minimum size then? Did you notice the same issue they reported?

**Comment by Sharcoux** [comment]
Actually, adding a margin to the slider itself can also solve the issue. I don't think that we should decide for the user about which margin should be set and where. I will close this.
