### ISSUE TITLE
Issue with npm i

### ISSUE THREAD

**Issue by MattinNajafi** [Sharcoux/slider#74]
Hi! Im trying to download the package and I get dependency issues. This is what i get `npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: x@1.0.0
npm ERR! Found: react-native@0.71.7
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.71.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.61.4" from @sharcoux/slider@6.1.2
npm ERR! node_modules/@sharcoux/slider
npm ERR!   @sharcoux/slider@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
....`

It seems like the react native is not updated, is there any way of fixing this?

**Comment by Sharcoux** [comment]
Oh, my bad about this. On it.

**Comment by Sharcoux** [comment]
Fixed

**Comment by MattinNajafi** [comment]
Thank you!
