### ISSUE TITLE
Trackmarks

### ISSUE THREAD

**Issue by MattinNajafi** [Sharcoux/slider#75]
Is there any way to add trackmarks, i cant find it in the documentation but that would be a great feature? trackmarks based on step and custom trackmarks

**Comment by Sharcoux** [comment]
You can probably make the track transparent and use your own component to represent the track the way you like.

**Comment by MattinNajafi** [comment]
How do you calculate each position of step, in that way I can insert steps on the same way so the thumb is same. Atm im using `justify-content: space-between` from beginning to end of slider, but there is some small differences of thumb position and the generated steps. (see image below)
<img width="438" alt="Skärmavbild 2023-07-06 kl  13 00 07" src="https://github.com/Sharcoux/slider/assets/55448006/e1a0be9a-4625-482b-8f66-126031fe9701">


`        <View
          pointerEvents="none"
          style={{
            justifyContent: 'space-between',
            flexDirection: 'row',
            marginTop: Platform.OS === 'ios' ? -17 : -14,
            zIndex: 2,
          }}
        >
          {options.map((i, index, arr) => {
            return (
              <View
                key={i}
                style={{
                  height: 50,
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                    <SliderTrackMark key={index} isTrue={getValue() === i} />
                    <Paragraph style={{ textAlign: 'center' }}>{i}</Paragraph>
              </View>
            );
          })}
        </View>
`
This is how i generate steps, Slider track mark is just a View that is green when true and else as the other trackmarks.

options is just an array containing number [0,1,2,3.....]

**Comment by Sharcoux** [comment]
Unfortunately, you cannot do it like that. You need the slider and your track to exactly align. The number of steps is (max - min) / step + 1. For instance, for a slider that allows [0, 1, 2], using a step of 1 and max: 2, min: 0, you get (2 - 0) / 1 + 1 = 3

Then, you need to pay attention that your bullet takes some space:

```
Slider track: -----
Visual track: ===
step: O

Incorrect:
|--------------|
|O==O==O|

Correct:

 |-----------|
O==O==O
```

To achieve this, you have 2 options:
- Or you increase the width of your visual track and move it some pixels to the left
- Or you position the marks using absolute positioning above the track

**Comment by Sharcoux** [comment]
Indeed. I forgot, but there is a small offset corresponding to the rounding of the track on the edges. Its width is the same as the track height.

Have a look [here](https://codesandbox.io/s/sharcoux-slider-demo-forked-x3xxlm?file=/src/App.js) for a working solution.

**Comment by Sharcoux** [comment]
Does this solve your problem?

**Comment by Sharcoux** [comment]
@MattinNajafi The new Version 7.0.1 provides native support for custom track marks. Enjoy.
