### ISSUE TITLE
Decimal step not working as expected

### ISSUE THREAD

**Issue by jacquesdev** [Sharcoux/slider#79]
**Describe the bug**
I'm passing in a step value which is being ignored/changed

**To Reproduce**
https://snack.expo.dev/DTj2WvRNl

**Expected behavior**
When I pass in a step of 0.25, I'd expect changing the slider to increase by these increments, currently it seems to be going up in increments of around 0.01

**Screenshots**
As I slide, I expect the number to go up in increments of 0.25
<img width="328" alt="Screenshot 2023-09-16 at 18 34 44" src="https://github.com/Sharcoux/slider/assets/7842197/3ccff3ab-37ea-4181-bb8d-9d2aeb26c18d">

**Please complete the following information:**
 - OS: iOS
 - @react-native-assets/slider version. Tried on 6.1.3, but also tried on latest with no difference

**Comment by Sharcoux** [comment]
Thanks for reporting. I'll check that out. I probably forgot to try those kind of values

**Comment by Sharcoux** [comment]
Fixed in version 7.0.4 

Don't hesitate to provide feedback.

**Comment by jacquesdev** [comment]
Thank you, that works well!
