### ISSUE TITLE
Package on npm has console.logs

### ISSUE THREAD

**Issue by kacperkapusciak** [Sharcoux/slider#8]
Thank you very much for this library - it has all the functionalities that I need. One issue is that the version (5.0.1) on npm has console.logs in the code. 
![image](https://user-images.githubusercontent.com/39658211/102467737-ef394000-4050-11eb-84ed-25a62d9ec986.png)
I've double-checked your code and you removed them in the code on GitHub. I've tried also to pull package directly from GitHub but without success. Could you update the package on npm?

**Comment by BIGbadEL** [comment]
That would be very useful.

**Comment by kacperkapusciak** [comment]
To people who are reading it in the future: you don't have to wait for maintainers to fix their library. You can patch node_modules directly with [patch-package](https://github.com/ds300/patch-package). I've applied [this fixes](https://github.com/Sharcoux/slider/commit/292ff5066f3a73b8766b54974b1492fb0df5471e) in useDrag.**js** and useThumb.**js**  in node_modules and works great.

**Comment by Sharcoux** [comment]
Oh my, sorry for that. I'm in holydays right now but let me fix that as soon as I get back to my computer.

**Comment by Sharcoux** [comment]
Version 5.0.3 resolves the issue.
