### ISSUE TITLE
Question about differences between v6 and v7

### ISSUE THREAD

**Issue by jacquesdev** [Sharcoux/slider#80]
I just have a general question. Are there any breaking changes between 6 and 7? I'm trying to ugrade to 7 but by just upgrading, the range slider becomes immoveable, so I'm not sure what I need to update from my implementation, or how this could happen

**Comment by Sharcoux** [comment]
Well, there is no breaking change per se, but there was a change in the structure that introduced a risk so I decided to use a new major.
Could you try to reproduce the problem in a minimal snack?

**Comment by jacquesdev** [comment]
ok, I will try and put something together

**Comment by Sharcoux** [comment]
There is a code sample in the Readme if you want to use this as a base.

**Comment by Sharcoux** [comment]
You can use this as a starting point: https://snack.expo.dev/@sharcoux/ff0473?platform=android

**Comment by Sharcoux** [comment]
Do you still have the problem?

**Comment by jacquesdev** [comment]
I was asking for a colleague and he said he would be in touch.

Thanks for your prompt response, really appreciate it

Feel free to close this one
