### ISSUE TITLE
I received a 'flexGrow: <None>' error when dragging the thumb.

### ISSUE THREAD

**Issue by jasonrockrabbit** [Sharcoux/slider#81]
I'm using v7.0.4, but I encountered this error with this version. The error is resolved when using v6.1.2. Can you help me understand why this happened?
![image](https://github.com/Sharcoux/slider/assets/141680752/c1138054-1730-4f3f-988e-60fa5d7ed999)

**Comment by Sharcoux** [comment]
I can help, but I might need a bit more data than this. Would you be able to reproduce the error in a snack expo? You can use this example: https://snack.expo.dev/@sharcoux/ff0473?platform=android

If you don't succeed to reproduce the error, please extract the code related to the slider. My guess is that you are passing a prop for minimumValue, maximumValue, value or step that is "not a number" `NaN`

**Comment by jasonrockrabbit** [comment]
I didn't encounter any errors in Expo Snack, but I'm using React Native CLI with TypeScript. I've set the 'minvalue' and 'maxvalue' with static values, but I'm still encountering the same error. Can you please check it on React Native CLI with TypeScript?
![image](https://github.com/Sharcoux/slider/assets/141680752/04e5805b-f163-4344-a001-d090e9ab5a84)

**Comment by Sharcoux** [comment]
I'm sorry, but I doubled check the code of the slider. The only reason you can see this error is if you provide a wrong set of values for maximumValue, minimumValue, step and value. I really don't see any other way and could not reproduce your bug. You can try to add some logs inside the RangeSlider implementation to monitor those values maybe.

**Comment by jasonrockrabbit** [comment]
I found the reason why this happened. This is because of the measure function. I tracked the measure function but I got pageX with undefined in RenderView.js. So, I added these lines in the node_modules, and then it worked. Can you add this to RenderView.js?
![image](https://github.com/Sharcoux/slider/assets/141680752/af8da137-c542-46e6-bc24-deb729d6ee5e)

**Comment by Sharcoux** [comment]
That's weird. I'll add that, but can you tell me on which platform you meet this problem? iOS? Android? Web?

**Comment by Sharcoux** [comment]
I released version 7.0.5 that should not contain the bug, but please answer me about the platform, it's very important.

**Comment by jasonrockrabbit** [comment]
I think it is fixed. It was happened on the android
