### ISSUE TITLE
Invisible Thumbs when CustomThumbs != undefined

### ISSUE THREAD

**Issue by BDKX16** [Sharcoux/slider#82]
Hi, first of all thanks for the library, I found it very useful, the problem im having is with the custom thumbs on IOS on the range Slider, (I haven't tried on android yet), the problem is that when i load a component on the CustomThumb the thumbs dissapear and the slider appears without any thumbs, the rest is working properly.

This is the component im rendering:

```
[...]
import { FontAwesome } from '@expo/vector-icons';

const IconSwitcher = (props) => {

  if (props.thumb === 'min') {
    return <FontAwesome name="moon-o" size={28} color="black" />; // renders the moon icon
  } else if (props.thumb === 'max') {
    return <FontAwesome name="sun-o" size={28} color="black" />; // renders the sun icon
  } else {
    return <FontAwesome name="sun-o" size={22} color="black" />; 
  }
};

export default IconSwitcher;
```

**Information:**
 - OS: iOS
 - @react-native-assets/slider version: 7.0.5

Any questions to solve this issue im open to answer it and I stay tuned to answer them

**Comment by Sharcoux** [comment]
Can you provide a snack expo that reproduces your issue?

**Comment by Sharcoux** [comment]
The example in the readme explains how you can use custom thumbs. If you still have trouble, try to look there. Without more information from you, I'll be closing this ticket.
