### ISSUE TITLE
Incorrect value being set

### ISSUE THREAD

**Issue by findhumane** [Sharcoux/slider#86]
**Describe the bug**

My use case is that the first time a user changes the slider, I want to show a popup and reset the slider's value back to what it was before. So I use `React.useRef` to save/update the current value of the slider any time it changes, and then when the value of the slider is updated, I check if the value has changed and try to set it back to the previously recorded value, but what I see is that `Slider` is using the incorrect value:

```js
import * as React from 'react';
import { Button, View } from 'react-native';
import { Slider } from '@react-native-assets/slider';

export default function App() {
  const [selectedValue, setSelectedValue] = React.useState(1);
  const previousValue = React.useRef(1);

  React.useEffect(() => {
    if (selectedValue != previousValue.current) {
      alert('changed from ' + previousValue.current + " to " + selectedValue);
      setSelectedValue(previousValue.current);
    }
  }, [selectedValue]);

  return (
    <View style={{ padding: 20 }}>
      <Slider
        value={selectedValue}
        onValueChange={(newValue) => {
          alert("Setting newValue " + newValue);
          previousValue.current = selectedValue;
          setSelectedValue(newValue);
        }}
        minimumValue={1}
        maximumValue={3}
        step={1}
        style={{ width: 100 }}
      />
    </View>
  );
}
```

**To Reproduce**
- Go to [this Snack](https://snack.expo.dev/@findhumane/testsliderstate)
- Click on the end of the slider in the last (3) position
- You should see an alert that writes, "Setting newValue 3"
- Click OK and then you should see an alert that writes, "changed from 1 to 3"
- Click OK and then you should see an alert that writes, "Setting newValue 3"
- As you can see from the code, the last alert is wrong. We know from the second alert that we are calling `setSelectedValue(1);`, but Slider's `onValueChange` is called with `3` in correctly.

**Expected behavior**

Slider should change the value to 1

**Screenshots**

N/A

**Please complete the following information:**
 - OS: Web
 - Browser: Firefox
 - @react-native-assets/slider version: latest

**Additional context**

I skipped the actual logic that handles the popup just the first time as this was enough to demonstrate the problem.

**Comment by Sharcoux** [comment]
You should be using `onSlidingComplete`. That will fix your issue.

**Comment by findhumane** [comment]
That worked, thanks!
