### ISSUE TITLE
no thumbs on Android device

### ISSUE THREAD

**Issue by avlonder** [Sharcoux/slider#9]
Hi @Sharcoux,

I experimented some more and found that, if I pick trackHeight > thumbSize, the circular shape of the thumb becomes clearly visible. It seems like some zIndex problem: the thumb is not an overlay with respect to the track.

The performance issue I was talking about [here](https://github.com/callstack/react-native-slider/issues/172#issuecomment-755726445), was caused by the thumb and track touchable area not being large enough, I guess. Maybe, you could add some padding which is touchable?

Thanks for the great work

**Comment by Sharcoux** [comment]
@avlonder Thanks for the feedback!

Can you provide me the exact parameters you are using so that I can replicate the issues? I should be able to provide a solution quickly.

**Comment by avlonder** [comment]
I upgraded to 5.0.3 and for some reason it works exactly as expected. Now, I can just increase the thumbs without having to increase the track, such that both problems are resolved at once. Sorry for the inconvenience. Earlier, I must have installed an older version or something. I cannot replicate the original problem stated above. So, I'm closing the issue.
