### ISSUE TITLE
CustomThumb is not working.

### ISSUE THREAD

**Issue by MattinNajafi** [Sharcoux/slider#92]
I cant make the CustomThumb to work, i have installed both 7.1.1 of 'react-native-assets/slider' and 'sharcoux/slider'. 
I have tried the slider with both packages. 

The CustomThumb with the text does not show. This is how my component looks like. (Im using android)

```
import { Slider } from "@sharcoux/slider";

const CustomThumb = ({ value }: any) => {
  return <Text>{value}</Text>;
};

<Slider
          style={styles.slider}
          minimumValue={0}
          maximumValue={100}
          value={values}
          CustomThumb={CustomThumb}
          step={10}
          thumbSize={50}
          onValueChange={setValues}
          minimumTrackTintColor="blue"
          maximumTrackTintColor="red"
        />
```

<img width="251" alt="Skärmavbild 2024-02-08 kl  14 10 07" src="https://github.com/Sharcoux/slider/assets/55448006/450d85ab-e0c3-4d65-9dd8-587f19810086">

**Comment by Sharcoux** [comment]
Hi

Your code is only partial, so I cannot help you.

Please edit [this Snack](https://snack.expo.dev/@sharcoux/sharcoux-slider-demo) just as explained in the issue template in order to reproduce the error.

**Comment by MattinNajafi** [comment]
```
import { View, Text, StyleSheet } from "react-native";
import React, { useState } from "react";
import { Slider } from "@sharcoux/slider";
import { SwedbankText } from "../../StyledText";
import CustomThumb from "../CustomThumb";

export default function Slider() {
 return (
        <Slider
          style={styles.slider}
          minimumValue={0}
          maximumValue={100}
          value={values}
          CustomThumb={({ value }) => {
            return <CustomThumb value={value} />;
          }}
          step={10}
          thumbSize={50}
          onValueChange={setValues}
          minimumTrackTintColor="blue"
          mint
          maximumTrackTintColor="red"
        />
        
         );
}

const styles = StyleSheet.create({
  slider: {
    marginHorizontal: -15,
    flex: 1,
  },
});

```

```
import { Text } from "react-native";
import React from "react";

export default function CustomThumb({ value }) {
  return (
    <Text
      style={{
        backgroundColor: "white",
        paddingHorizontal: 15,
        borderRadius: 8,
      }}
    >
      {value}
    </Text>
  );
}

```

Here you have the entire code. I cannot see any reason why it shouldnt work, on the link you provided it is working but i cannot review it with android only web. I think the issue is with android/ios.

**Comment by MattinNajafi** [comment]
```
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-assets/slider": "^7.1.1",
    "@react-native-community/slider": "^4.5.0",
    "@react-navigation/native": "^6.0.2",
    "@sharcoux/slider": "^7.1.1",
```

This is my package.json. Do you need to see anything more? does it work for you with android device?

**Comment by Sharcoux** [comment]
Please, share the snack with your own code. There are tabs that will let you test on Android and iOS. Also, using this:

```
          CustomThumb={({ value }) => {
            return <CustomThumb value={value} />;
          }}
```

Is a bad idea because you will be creating a new component at each render. Use `CustomThumb={CustomThumb}`.

**Comment by MattinNajafi** [comment]
Strange, because the code i paste inside the snack work in the link you provided but not when im using android studio small desktop..

**Comment by Sharcoux** [comment]
Generally, this means that the problem lies in your project or environment.
