### ISSUE TITLE
[RangeSlider] The accessibility of the min thumb doesn't seem to work

### ISSUE THREAD

**Issue by linhvovan29546** [Sharcoux/slider#95]
**Describe the bug**
The accessibility of the min thumb doesn't seem to work; it appears that only accessibility for the max thumb is supported

**To Reproduce**
- I cannot reproduce this issue. Therefore, I tested it on my website.
- Press the `Tab` key to focus on the thumb button.
- Press the `ArrowRight` or `ArrowLeft` key to slide the thumb.

**Expected behavior**
The accessibility should work for both the `min` and `max` thumbs as [expected](https://github.com/Sharcoux/slider/assets/84692183/6c17493a-fcc5-4c0e-ac4b-5b985025c9da). 

**Screenshots**

![Screen Recording 2024-04-26 at 4 45 03 PM](https://github.com/Sharcoux/slider/assets/84692183/9cc93f43-6d72-4c57-a614-4d70a01fc25c)

**Please complete the following information:**
 - OS: Web
 - Browser all
 - @react-native-assets/slider version ["latest"]

**Additional context**
I can not reproduce on Snack, so i reproduce on my website.
Noted: I used this [example](https://github.com/Sharcoux/slider?tab=readme-ov-file#range-slider) to reproduce

**Comment by linhvovan29546** [comment]
@Sharcoux My approach is that we need to detect which thumb component is currently focused, and whenever the handleAccessibilityKeys function is invoked, we check which thumb (min/max) is in focus to increment or decrement the value accordingly. If my approach is correct, may I create a PR for it?

**Comment by Sharcoux** [comment]
I fixed it. Please test version 7.2.0 and report any issue you might encounter.

**Comment by linhvovan29546** [comment]
Thanks @Sharcoux , I've tested on v7.2.0, and it seems okay. However, I have a question: the accessibility action does not increase or decrease if the `min` or `max` thumb is in the same `position` despite `crossingAllowed` being set to `true`([Please view the attached video for clarity](https://github.com/Sharcoux/slider/assets/84692183/e2ad518c-a714-4aad-a778-166e415bfa9a)). Additionally, I noticed there is a `console.log `[here](https://github.com/Sharcoux/slider/blob/master/src/hooks/useRange.ts#L25) (I think you are missing that), could you remove it?

**Comment by Sharcoux** [comment]
Ok, I fixed some problems. However, having the accessibility actions enable the thumbs to cross would require major changes that I'm not ready to implement. You can give it a try if you want and suggest a PR.

You can test the fixes in the version 7.2.1

**Comment by linhvovan29546** [comment]
@Sharcoux Okay, v7.2.1 looks good to me. I'll submit a PR for this if possible

**Comment by Sharcoux** [comment]
I'll close this. Open a PR if you want to discuss the thumb crossing.
